ga_code: UA-xxx-xxx

languages: [en, hu]

collections:
  - works

gems:
  - jekyll-redirect-from

defaults:
  - scope:
      path: 'en'
    values:
      layout: default
      lang: en

  - scope:
      path: 'hu'
    values:
      layout: default
      lang: hu
