ga_code: UA-xxx-xxx

languages: [en, hu]

collections:
  - works

gems:
  - jekyll-redirect-from

defaults:
  - scope:
      path: 'en'
    values:
      layout: default
      lang: en

  - scope:
      path: 'hu'
    values:
      layout: default
      lang: hu

trans:
  en:
    nav:
      home: henrik martin
      selected: selected
      cv: cv
      portfolio: portfolio
      works: works
      actual: actual
      texts: texts
      contact: contact
      links: links
  hu:
    nav:
      home: martin henrik
      selected: válogatás
      cv: cv
      portfolio: portfólió
      works: művek
      actual: aktuális
      texts: írások
      contact: kapcsolat
      links: linkek

    

